name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - "test/refs"
      - "releases/*"

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run prepare
  test: # validate the action does what it meant to do
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
